language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=x86

android:
  components:
    - build-tools-21.0.1
    - android-21
    - extra-android-m2repository
    - sys-img-x86-android-14
    - sys-img-x86-android-16
    - sys-img-x86-android-19
    - sys-img-x86-android-21

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  # Run tests, and do a logcat dump if anything fails
  - ./gradlew connectedCheck --info || (adb logcat -d && echo "TESTS FAILED" && exit 1)
