language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.0.1
    - android-21
    - extra-android-m2repository
    # Use a mix of ARM and x86 processors, and different API levels
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-v7a-android-19
    - sys-img-armeabi-v7a-android-16
    - sys-img-x86-v7a-android-14

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
